name: Build Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 3'

jobs:
  docker:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - php_version: '8.4'
            is_latest: true
          - php_version: '8.3'
            is_latest: false
          - php_version: '8.2'
            is_latest: false
          - php_version: '8.1'
            is_latest: false
          - php_version: '8.0'
            is_latest: false
          - php_version: '7.4'
            is_latest: false
          - php_version: '7.3'
            is_latest: false
          - php_version: '7.2'
            is_latest: false
          - php_version: '7.1'
            is_latest: false
          - php_version: '7.0'
            is_latest: false
          - php_version: '5.6'
            is_latest: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # BUILD AMD64 IMAGE
      - name: Build and push lemp image - amd64
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
              PHP_VERSION=${{ matrix.php_version }}
          tags: |
              fbraz3/lnmp:${{ matrix.php_version }}-amd64

      # RESERVED FOR FUTURE TESTING
      # create info.php file
      # run image on daemon mode, name container as lnmp-amd64, bind 80 port to 8080, map info.php to /app/public
      # sleep a little bit to allow the image to start
      # test php version
      # test daemons: nginx, php-fpm, mariaDB
      # test nginx: http://localhost:8080
      # test php-fpm: http://localhost:8080/info.php
      # run "show databases" command against mariadb server

      # BUILD ARM64 IMAGE
      - name: Build and push lemp image - arm64
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
              PHP_VERSION=${{ matrix.php_version }}
          tags: |
              fbraz3/lnmp:${{ matrix.php_version }}-arm64

      # RESERVED FOR FUTURE TESTING
      # same as amd64 tests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push lemp image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            fbraz3/lnmp:${{ matrix.php_version }}
            fbraz3/lemp:${{ matrix.php_version }}
            ${{ matrix.is_latest && 'fbraz3/lnmp:latest' || '' }}
            ${{ matrix.is_latest && 'fbraz3/lemp:latest' || '' }}