name: Build Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 3'

jobs:
  docker:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - php_version: '8.4'
            is_latest: true
          - php_version: '8.3'
            is_latest: false
          - php_version: '8.2'
            is_latest: false
          - php_version: '8.1'
            is_latest: false
          - php_version: '8.0'
            is_latest: false
          - php_version: '7.4'
            is_latest: false
          - php_version: '7.3'
            is_latest: false
          - php_version: '7.2'
            is_latest: false
          - php_version: '7.1'
            is_latest: false
          - php_version: '7.0'
            is_latest: false
          - php_version: '5.6'
            is_latest: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            fbraz3/lnmp:${{ matrix.php_version }}
            fbraz3/lemp:${{ matrix.php_version }}
            ${{ matrix.is_latest && 'fbraz3/lnmp:latest' || '' }}
            ${{ matrix.is_latest && 'fbraz3/lemp:latest' || '' }}