name: Build Docker Image - PHP 8.3

on:
  workflow_dispatch:
  schedule:
    - cron: '10 10 * * 3'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [linux/amd64, linux/arm64]
        php_version: [8.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.architecture }}
          context: .
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          tags: |
            fbraz3/lnmp:${{ matrix.php_version }}
            fbraz3/lemp:${{ matrix.php_version }}
            fbraz3/lnmp:${{ matrix.php_version }}-${{ matrix.architecture | replace('linux/', '') }}
            fbraz3/lemp:${{ matrix.php_version }}-${{ matrix.architecture | replace('linux/', '') }}
            ${{ matrix.php_version == '8.3' && 'fbraz3/lnmp:latest' || '' }}
            ${{ matrix.php_version == '8.3' && 'fbraz3/lemp:latest' || '' }}
            ${{ matrix.php_version == '8.3' && format('fbraz3/lnmp:latest-{0}-{1}', 'latest', matrix.architecture | replace('linux/', '')) || '' }}
            ${{ matrix.php_version == '8.3' && format('fbraz3/lemp:latest-{0}-{1}', 'latest', matrix.architecture | replace('linux/', '')) || '' }}
